name: Deploy
on:
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      PRODUCTION: true
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/bake-action@v3
      with:
        push: true
        files: compose.prod.yml
        set: |
          *.cache-to=type=gha,scope=cached-stage,mode=max
          *.cache-from=type=gha,scope=cached-stage

  deploy:
     needs: build
     runs-on: self-hosted
     env:
       PRODUCTION: true
       POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
       MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
       POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
     steps:
     - uses: actions/checkout@v3
       with:
         submodules: true

     - name: Login to Github Packages
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Deploy with docker-compose
       run: |
         docker compose -f compose.prod.yml pull
         docker compose -f compose.prod.yml up -d --remove-orphans
         docker container prune -f
         docker image prune -af
         docker builder prune
